import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/app/_components/Header";
import styles from "@/app/layout.module.scss";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Tatsuhiko Arakawa's Potofolio",
	description:
		"This is Tatsuhiko Arakawa's potofolio site generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${styles.body} ${geistSans.variable} ${geistMono.variable}`}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
