import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { ReactNode } from "react";
import { Suspense } from "react";
import "@/app/globals.css";
import Footer from "@/app/_components/_organisms/Footer/Footer";
import Header from "@/app/_components/_organisms/Header/Header";
import styles from "@/app/layout.module.scss";
import Loading from "@/app/loading";
import GlobalDialog from "@/components/atoms/Dialog/GlobalDialogWrapper";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Tatsuhiko Arakawa's Potofolio",
	description:
		"This is Tatsuhiko Arakawa's potofolio site generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${styles.body} ${geistSans.variable} ${geistMono.variable}`}
			>
				<Header />
				<Suspense fallback={<Loading />}>{children}</Suspense>
				<Footer />
				<GlobalDialog />
			</body>
		</html>
	);
}
